version: '3.8'

services:
  my-node-app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGODB_URI: "mongodb://mongo:27017/mydatabase"
      RABBITMQ_URI: "amqp://rabbitmq"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data:
