version: '3.8'

services:
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: "123123"
      MONGO_INITDB_ROOT_USERNAME: "root"

  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  my-node-app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mongo
      - rabbitmq
    




volumes:
  mongo_data:
