apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: my-node-app
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-node-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe convert
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.service: my-node-app
    spec:
      containers:
        - env:
            - name: AMQP_HOST
              value: rabbitmq
            - name: DB_URL
              value: mongodb://mongo:27017/inventory
          image: my-node-app
          name: my-node-app
          ports:
            - containerPort: 8090
          resources: {}
      restartPolicy: Always
status: {}
